BEGIN TRANSACTION;


DELETE FROM DWH.FACT_EVENT_REPLACEMENT_SHOPPER WHERE event_date_pt = '{start_date}';

INSERT INTO DWH.FACT_EVENT_REPLACEMENT_SHOPPER
(
    source_file_folder  ,
	source_file_name  ,
	data_source  ,
	data_source_user_tracking_id  ,
	event_type  ,
	event_name  ,
	event_id  ,
	user_id  ,
	shopper_id  ,
	shopper_roles  ,
	shopper_shift_id  ,
	shift_type  ,
	batch_id  ,
	platform  ,
	app_version  ,
	event_date_time_utc  ,
	event_date_time_pt  ,
	event_date_utc ,
	event_date_pt ,
	event_sent_date_time_utc  ,
	event_received_date_time_utc  ,
	source_type  ,
	source_value,
	parent_id  ,
	country_id  ,
	currency  ,
	zip_code  ,
	zone_id  ,
	warehouse_id  ,
	inventory_area_id  ,
	replacements_view_id  ,
	order_id  ,
	order_delivery_id  ,
	order_item_id  ,
	num_replacements  ,
	total_replacements  ,
	replacement_item_impression_id  ,
	from_item_modal  ,
	fetch_error_ind  ,
	item_id  ,
	item_card_impression_display_position  ,
	item_card_impression_model_score  ,
	item_card_impression_impression_attributes  ,
	item_card_impression_grid_row  ,
	item_card_impression_id  ,
	item_card_impression_grid_column  ,
	item_card_impressions_item_id  ,
	dwh_created_date_time_utc  ,
	search_term )
SELECT
    CASE WHEN data_source = 'segment' THEN 
	dateadd(ms, split_part(source_file_name, '.', 1), '1970-01-01')
	::date::varchar ELSE source_file_name END as source_file_folder,
	source_file_name  ,
	data_source  ,
	data_source_user_tracking_id  ,
	event_type  ,
	event_name  ,
	event_id  ,
	user_id  ,
	shopper_id  ,
	shopper_roles  ,
	shopper_shift_id  ,
	shift_type  ,
	batch_id  ,
	platform  ,
	app_version  ,
	event_date_time_utc  ,
	event_date_time_pt  ,
	event_date_time_utc::date as event_date_utc,
	event_date_time_pt::date as event_date_pt,
	event_sent_date_time_utc  ,
	event_received_date_time_utc  ,
	source_type  ,
	source_value,
	parent_id  ,
	country_id  ,
	currency  ,
	zip_code  ,
	zone_id  ,
	warehouse_id  ,
	inventory_area_id  ,
	replacements_view_id  ,
	order_id  ,
	order_delivery_id  ,
	order_item_id  ,
	num_replacements  ,
	total_replacements  ,
	replacement_item_impression_id  ,
	from_item_modal  ,
	fetch_error_ind  ,
	item_id  ,
	TRY_TO_NUMBER(i.value:display_position::VARCHAR) as item_card_impression_display_position  ,
	TRY_TO_NUMERIC(i.value:model_score::VARCHAR) as item_card_impression_model_score  ,
	i.value:impression_attributes::varchar as item_card_impression_impression_attributes,
	TRY_TO_NUMBER(i.value:grid_row::VARCHAR) as item_card_impression_grid_row  ,
	i.value:item_card_impression_id::varchar as item_card_impression_id  ,
	TRY_TO_NUMBER(i.value:grid_column::VARCHAR) as item_card_impression_grid_column  ,
	TRY_TO_NUMBER(i.value:item_id::VARCHAR) as item_card_impressions_item_id  ,
    cast(current_timestamp() as timestamp_ntz(9)) as dwh_created_date_time_utc,
    search_term
FROM
dwh.vw_replacement_shopper d,
LATERAL FLATTEN (INPUT => d.item_card_impressions, OUTER => TRUE) i
WHERE event_date_pt = '{start_date}'
AND event_name in ('replacements.replacements_view', 'replacements.select_replacement', 'replacements.view_replacements', 'replacements.item_card_impressions')
;

COMMIT ;