-- FIXME. databricks.migrations.unsupported  Named  paramaters in function call
SELECT
	ARRAY_TO_STRING(array_slice(split(source_file_name, '-' ), 5, 8), '') as source_file_folder,
	source_file_name,
	data_source,
	data_source_user_tracking_id,
	event_type,
	event_name,
	event_id,
	visit_token,
	visitor_token,
	user_id,
	platform,
	api_version,
	app_version,
	event_date_time_utc,
	event_date_time_pt,
	event_date_time_utc::DATE as event_date_utc,
	event_date_time_pt::DATE as event_date_pt,
	event_sent_date_time_utc,
	event_received_date_time_utc,
	source_type,
	source_value,
	parent_id,
	country_id,
	currency,
	zip_code,
	zone_id,
	warehouse_id,
	whitelabel_retailer,
	whitelabel_id,
	wl_exclusive,
	TRY_TO_NUMBER(inventory_area_id) as inventory_area_id,
	replacements_view_id,
	num_replacements,
	total_replacements,
	item_card_impression_id as replacement_item_impression_id,
	from_item_modal,
	fetch_error_ind,
	item_id,
	order_id,
	order_delivery_id,
	order_item_id,
	i.value:display_position\:\:NUMBERas item_card_impression_display_position,
    i.value:replacement_score::FLOAT as item_card_impression_model_score,
    i.value:impression_attributes::VARCHAR as item_card_impression_impression_attributes,
    i.value:grid_row\:\:NUMBERas item_card_impression_grid_row,
    i.value:item_card_impression_id::VARCHAR as item_card_impression_id,
    i.value:grid_column\:\:NUMBERas item_card_impression_grid_column,
    i.value:item_id\:\:NUMBERas item_card_impressions_item_id,
    cast(current_timestamp() as timestamp_ntz(9)) as dwh_created_date_time_utc,
    i.value:propensity::FLOAT as propensity,
	candidates
FROM
dwh.vw_replacement_customer  d,
-- FIXME databricks.migration.unsupported.function LATERAL_FLATTEN
LATERAL FLATTEN (INPUT => d.item_card_impressions, OUTER => TRUE) i
WHERE event_date_pt = '{start_date}' and
(event_name in ('store.replacements_view', 'store.select_replacement', 'store.view_replacements', 'store.reject_replacement', 'store.view_more_replacements')
OR  (event_name in ('store.item_card_impressions') and source_type in ('checkout_replacements',
                                                                   'post_checkout_replacements',
                                                                   'order_item_changes',
                                                                    'low_stock',
                                                                    'low_stock_more_options',
                                                                    'low_stock_more_options_search',
                                                                    'high_risk_pair',
                                                                    'high_risk_more_options',
                                                                    'high_risk_more_options_search')));

;